### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by samrawitergrtr** [RockyXu66/Faster_RCNN_for_Open_Images_Dataset_Keras#57]
Hi, I was trying to run in my own datasets and the Object_Detection_DataPreprocessing.ipynb runs correctly but when i try to run the training file i face with the problem TypeError: 'NoneType' object is not iterable.
![problem1](https://user-images.githubusercontent.com/60253058/80910514-bed0ab80-8ce4-11ea-9dd4-02781fa486ef.PNG)

The only thing that i change is, the datasets with single class or label and i am using local machine.  
 I don't know how to fix this.Can you help?

**Comment by Arthur023** [comment]
Sometimes I have errors like this when I'm running out of memory.  Maybe try shutting down all your other notebooks and run it again.

**Comment by samrawitergrtr** [comment]
i tried that still the problem is not fixing so i was wondering if maybe the statement that we caked if the class_name == 'bg' is not clear.Because i created the single label datasets using Object_Detection_DataPreprocessing.ipynb and it is correctly created but i have no class or label name called 'bg'  is their any explanation where does 'bg' comes from?

**Comment by Arthur023** [comment]
You don't need a class bg. The bg stands for back ground and the model creates that class itself. So then your RPN is finding some boxes it could be that there is nothing in the box he is finding so the bg class gives the classifier model a chance to classify it als back ground.

I read somewhere that it could help to uninstall and install the following things. After I started up the notebook for the first time I will always have to uninstall and install ipykernel before the notebook wants to work. So you could give that a try 

•	ipykernel
•	ipython
•	jupyter_client
•	jupyter_core
•	traitlets
•	ipython_genutils

Also make sure that there are not enters at the end of your txt file with the data in. But I assume you have more than 3 lines in that file so that's not gonna be the problem

**Comment by samrawitergrtr** [comment]
I tried it but noting changed but in the Object_Detection_DataPreprocessing.ipynb, when i tried to create .txt file i found the same problem because of .csv file is not directed correctly. So i tried to check everything so if you see any difference you will tell me.
In def get_data(input_path)
1.The input_path is a directory of /annotation.txt file
2. I think the problem is in reading image using cv2 in 
if filename not in all_imgs:
Does the filename locate the image location like 
\Faster_RCNN_for_Open_Images_Dataset_Keras/dataset/annotation.csv\1.jpg
Because it is not reading the image it returns Noon insted of array and it happens when the directory or image name is not correct. So does the filename only contains image name only(e.g dog.jpg ) or the row in .txt file ( e.g \Faster_RCNN_for_Open_Images_Dataset_Keras/dataset/annotation.csv\1.jpg)    
Can you explain me what should img = cv2.imread(filename) return and filename ?

**Comment by samrawitergrtr** [comment]
I found the problem, like i said false directory in the .txt file( the path name was not correct ) so that is why it cause the problem. Thank you for your help!
